"""
ArtifactKnowledgeBase
"""
from __future__ import annotations

from typing import Any, Dict

GENERIC_FALLBACK: Dict[str, Any] = {
    "finding_type": "Unclassified Network Artifact",
    "category": "network",
    "title": "Unclassified Network Artifact",
    "description": "Raw artifact collected from a network device; no knowledge-base entry exists yet for this artifact key.",
    "why_this_matters": "Not yet documented — review the raw evidence directly.",
    "what_is_this": "An artifact collected by the Network Devices module that hasn't been catalogued in the knowledge base yet.",
    "normal_behaviour": "",
    "suspicious_behaviour": "",
    "mitre_technique_id": None,
    "mitre_technique": None,
    "mitre_tactic": None,
    "base_risk_score": 0,
    "recommendations": [],
    "findingtags": ["forensicator", "network", "uncatalogued"],
}

# ── Baseline collected artifacts (one per collectors/cisco_ios.py COMMANDS key) ──

_BASELINE: Dict[str, Dict[str, Any]] = {
    "version": {
        "finding_type": "Device Version and Hardware Information",
        "title": "Device Version and Hardware Information",
        "description": "Software version, uptime, and hardware identity reported by the device.",
        "why_this_matters": "Establishes exactly what's running for the rest of the investigation, and whether the device is on a version with known CVEs.",
        "what_is_this": "The device's version/hardware summary (OS version, uptime, hardware model, serial number) — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "A version matching the organization's approved software baseline.",
        "suspicious_behaviour": "An unexpectedly old version, an uptime that doesn't match a known maintenance window, or hardware/serial that doesn't match asset inventory.",
        "recommendations": [{"priority": "info", "action": "Cross-reference the reported version against the vendor's security advisories.", "reason": "Confirms whether this device is exposed to any known, unpatched vulnerability."}],
        "findingtags": ["network", "version", "hardware"],
    },
    "running-config": {
        "finding_type": "Full Running Configuration",
        "title": "Full Running Configuration",
        "description": "The device's complete active configuration, collected for keyword/drift review and as the source for several detection rules.",
        "why_this_matters": "The single most information-dense artifact collected — nearly every other finding on this device (ACLs, AAA, SNMP, local accounts) is derived from this text.",
        "what_is_this": "The device's full active configuration — see this finding's source.command for the exact command used on this platform (e.g. `show running-config` on Cisco/Arista, `show configuration` on Junos).",
        "normal_behaviour": "Matches the organization's configuration baseline/template for this device role.",
        "suspicious_behaviour": "Unexpected ACL entries, new NAT/PAT rules, unrecognized tunnel interfaces, or any drift from a known-good baseline.",
        "recommendations": [{"priority": "medium", "action": "Diff this configuration against the last known-good baseline for this device.", "reason": "Config drift is one of the most reliable indicators of unauthorized access to network infrastructure."}],
        "findingtags": ["network", "configuration"],
    },
    "sessions": {
        "finding_type": "Active Management Sessions",
        "title": "Active Management Sessions",
        "description": "Users/sessions currently logged into the device's management plane.",
        "why_this_matters": "Shows exactly who is on the device right now — directly relevant if this investigation is time-sensitive.",
        "what_is_this": "Active management-plane sessions — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Sessions from known administrator source addresses during expected hours.",
        "suspicious_behaviour": "A session from an unrecognized source address, or at an unusual time.",
        "recommendations": [],
        "findingtags": ["network", "sessions"],
    },
    "arp-table": {
        "finding_type": "ARP Cache",
        "title": "ARP Cache",
        "description": "IP-to-MAC mappings currently known to the device.",
        "why_this_matters": "Useful for tracing which physical/virtual host owned an IP address at collection time — relevant for pivoting to a specific endpoint.",
        "what_is_this": "The device's ARP cache — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Expected hosts, no MAC address duplicated across multiple IPs.",
        "suspicious_behaviour": "The same MAC address claiming multiple IPs (possible ARP spoofing), or an unrecognized vendor OUI on a supposedly locked-down segment.",
        "recommendations": [],
        "findingtags": ["network", "arp"],
    },
    "mac-address-table": {
        "finding_type": "MAC Address Table",
        "title": "MAC Address Table",
        "description": "Learned MAC addresses and the switchports they were seen on.",
        "why_this_matters": "Ties a MAC address to a physical port — useful for locating a device physically during response.",
        "what_is_this": "Learned MAC addresses and the switchports they were seen on — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Expected device count per port; access ports show one MAC, not dozens.",
        "suspicious_behaviour": "An access port suddenly showing many MAC addresses (possible rogue switch/hub plugged in), or MAC flapping between ports.",
        "recommendations": [],
        "findingtags": ["network", "mac-table"],
    },
    "ip-route": {
        "finding_type": "IP Routing Table",
        "title": "IP Routing Table",
        "description": "The device's current routing table.",
        "why_this_matters": "An unexpected route (especially a default route pointing somewhere new) can silently redirect traffic for interception.",
        "what_is_this": "The device's routing table — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Matches the expected routing design for this device/segment.",
        "suspicious_behaviour": "A static route not present in the baseline, or a default route pointing to an unexpected next-hop.",
        "recommendations": [],
        "findingtags": ["network", "routing"],
    },
    "access-lists": {
        "finding_type": "Access Control Lists",
        "title": "Access Control Lists",
        "description": "ACLs currently configured and active on the device.",
        "why_this_matters": "ACLs are often the only thing standing between a segment and the rest of the network — an overly broad rule undoes segmentation entirely.",
        "what_is_this": "The device's active traffic-filtering policy (ACLs on Cisco/Arista, firewall filters on Junos) — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Scoped permit/deny rules matching the intended security policy.",
        "suspicious_behaviour": "A broad `permit ip any any`-style rule, or an ACL that was recently modified without a corresponding change ticket.",
        "recommendations": [],
        "findingtags": ["network", "acl"],
    },
    "logging": {
        "finding_type": "Local Log Buffer",
        "title": "Local Log Buffer",
        "description": "Recent entries from the device's local logging buffer.",
        "why_this_matters": "May contain direct evidence of the incident (failed logins, config changes, interface flaps) even before any dedicated detection rule fires.",
        "what_is_this": "Recent entries from the device's local log buffer — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Routine operational messages.",
        "suspicious_behaviour": "Repeated authentication failures, unexpected config-change log lines, or a gap in the log timeline (possible log tampering).",
        "recommendations": [],
        "findingtags": ["network", "logging"],
    },
    "cdp-neighbors": {
        "finding_type": "CDP Neighbor Topology",
        "title": "CDP Neighbor Topology",
        "description": "Directly-connected neighbor devices as seen via CDP.",
        "why_this_matters": "An unexpected neighbor on a port that should be an end-host port can indicate a rogue switch or access point physically plugged into the network.",
        "what_is_this": "The output of `show cdp neighbors detail`.",
        "normal_behaviour": "Only expected infrastructure devices appear as neighbors on trunk/uplink ports; end-host ports show no CDP neighbor at all.",
        "suspicious_behaviour": "A switch or AP appearing as a neighbor on a port that's supposed to be a single end-host access port.",
        "recommendations": [],
        "findingtags": ["network", "topology", "cdp"],
    },
    "lldp-neighbors": {
        "finding_type": "LLDP Neighbor Topology",
        "title": "LLDP Neighbor Topology",
        "description": "Directly-connected neighbor devices as seen via LLDP — the vendor-neutral equivalent of CDP, used by Junos and available on Cisco/Arista alongside CDP.",
        "why_this_matters": "An unexpected neighbor on a port that should be an end-host port can indicate a rogue switch or access point physically plugged into the network.",
        "what_is_this": "The output of `show lldp neighbors detail`.",
        "normal_behaviour": "Only expected infrastructure devices appear as neighbors on trunk/uplink ports; end-host ports show no LLDP neighbor at all.",
        "suspicious_behaviour": "A switch or AP appearing as a neighbor on a port that's supposed to be a single end-host access port.",
        "recommendations": [],
        "findingtags": ["network", "topology", "lldp"],
    },
    "snmp-config": {
        "finding_type": "SNMP Configuration",
        "title": "SNMP Configuration",
        "description": "The device's current SNMP configuration and community/user list.",
        "why_this_matters": "SNMP with a weak or default community string is a well-known, trivial way to read (and on some setups, write) device configuration remotely.",
        "what_is_this": "The device's SNMP configuration — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "SNMPv3 with unique, non-default credentials, or SNMP disabled entirely.",
        "suspicious_behaviour": "A default community string (`public`/`private`), or SNMPv1/v2c in use instead of v3.",
        "recommendations": [],
        "findingtags": ["network", "snmp"],
    },
    "ssh-config": {
        "finding_type": "SSH Management Configuration",
        "title": "SSH Management Configuration",
        "description": "The device's SSH server configuration (version, timeouts, authentication retries).",
        "why_this_matters": "Confirms whether the intended secure management protocol is actually in effect and correctly hardened.",
        "what_is_this": "The device's SSH/management-access configuration — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "SSHv2 only, with a reasonable authentication-retry limit.",
        "suspicious_behaviour": "SSHv1 still permitted, or an unusually high authentication-retry count.",
        "recommendations": [],
        "findingtags": ["network", "ssh"],
    },
    "clock": {
        "finding_type": "Device Clock",
        "title": "Device Clock",
        "description": "The device's current system clock reading.",
        "why_this_matters": "Every timestamp collected from this device (logging, sessions, ARP) is only as trustworthy as this clock — a skewed clock undermines cross-device timeline correlation.",
        "what_is_this": "The device's current system clock reading — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Matches actual current time within a few seconds.",
        "suspicious_behaviour": "A clock that's significantly off from actual time.",
        "recommendations": [],
        "findingtags": ["network", "time"],
    },
    "ntp-associations": {
        "finding_type": "NTP Time Synchronization",
        "title": "NTP Time Synchronization",
        "description": "The device's configured NTP peers and their sync status.",
        "why_this_matters": "No working NTP sync means this device's timestamps can silently drift, undermining log correlation across the environment during an incident (the same concern the Windows/Linux/macOS collectors flag when NTP is misconfigured).",
        "what_is_this": "The device's configured NTP peers and sync status — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "At least one NTP peer reachable and synchronized (marked with `*` in IOS output).",
        "suspicious_behaviour": "No peers configured, or all configured peers unreachable/unsynchronized.",
        "recommendations": [{"priority": "low", "action": "Configure and verify at least one reachable, synchronized NTP source.", "reason": "Reliable timestamps are a prerequisite for correlating this device's logs with everything else collected during the investigation."}],
        "findingtags": ["network", "ntp", "time"],
    },
}

# ── Detection-rule findings (keyed by the rule id in rules/rules.json) ──

_RULE_FINDINGS: Dict[str, Dict[str, Any]] = {
    "insecure-mgmt-plane": {
        "finding_type": "Insecure Management Plane",
        "title": "Telnet Enabled or VTY Lines Without Source Restriction",
        "description": "The device's running-config permits Telnet management access, and/or has VTY lines with no access-class restricting which source addresses may connect.",
        "why_this_matters": "Telnet transmits credentials in plaintext, and an unrestricted VTY line means anyone who can route to the device's management IP can attempt to log in — both dramatically widen the attack surface on the device that, if compromised, controls the network itself.",
        "what_is_this": "A regex scan of `show running-config` for `transport input telnet` (or `transport input all`) on a `line vty` block, and for `line vty` blocks with no `access-class` statement.",
        "normal_behaviour": "`transport input ssh` only, with every VTY line restricted by an `access-class` ACL to known management-source addresses.",
        "suspicious_behaviour": "Telnet permitted, or a VTY line reachable from any source address.",
        "mitre_technique_id": "T1021.001",
        "mitre_technique": "Remote Services: Remote Desktop Protocol",
        "mitre_tactic": "Lateral Movement",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Remove `transport input telnet` from every VTY line; restrict to `transport input ssh`.", "reason": "Telnet's plaintext credentials can be captured by anyone able to observe the management network path."},
            {"priority": "high", "action": "Apply an `access-class` ACL to every VTY line, scoped to known management-source addresses only.", "reason": "Prevents management-plane login attempts from anywhere other than trusted, expected sources."},
        ],
        "findingtags": ["network", "management-plane", "telnet", "mitre-lateral-movement"],
    },
    "weak-snmp-community": {
        "finding_type": "Weak or Default SNMP Community",
        "title": "Default or Weak SNMP Community String In Use",
        "description": "The device's running-config includes an SNMP community string matching a common default (`public`/`private`), and/or SNMPv1/v2c is configured instead of SNMPv3.",
        "why_this_matters": "A default SNMP community string is one of the most well-known, trivially exploitable network-device weaknesses — it can allow an attacker to read (and depending on the community's permissions, write) device configuration without ever needing to log in.",
        "what_is_this": "A regex scan of `show running-config` for `snmp-server community public`/`private` lines and for the absence of any `snmp-server group ... v3` configuration.",
        "normal_behaviour": "SNMPv3 with unique, non-default credentials, or SNMP disabled entirely if not needed.",
        "suspicious_behaviour": "Any `snmp-server community` line using `public` or `private`, or SNMPv1/v2c configured at all.",
        "mitre_technique_id": "T1552.001",
        "mitre_technique": "Unsecured Credentials: Credentials In Files",
        "mitre_tactic": "Credential Access",
        "base_risk_score": 70,
        "recommendations": [
            {"priority": "high", "action": "Remove any `public`/`private` SNMP community and migrate to SNMPv3 with unique credentials.", "reason": "Default community strings are the first thing scanned for by both automated malware and manual attackers targeting network infrastructure."},
        ],
        "findingtags": ["network", "snmp", "credential-access"],
    },
    "unauthorized-local-accounts": {
        "finding_type": "Unauthorized Local Account",
        "title": "Local Account Not on the Expected Baseline",
        "description": "A `username` entry exists in running-config that isn't present in this device's (or the global) expected_local_users allow-list in config.json.",
        "why_this_matters": "An unexpected local account is one of the most direct signs of unauthorized persistent access to network infrastructure — unlike a compromised centralized-AAA credential, a rogue local account survives even if every other credential in the environment is rotated.",
        "what_is_this": "The set of local user accounts extracted from this device's running config (syntax varies by vendor — see this finding's source.command), diffed against config.json's expected_local_users baseline for this device.",
        "normal_behaviour": "Every local account present matches the configured baseline exactly.",
        "suspicious_behaviour": "Any local account present in running-config that isn't in the baseline list.",
        "mitre_technique_id": "T1136.001",
        "mitre_technique": "Create Account: Local Account",
        "mitre_tactic": "Persistence",
        "base_risk_score": 90,
        "recommendations": [
            {"priority": "critical", "action": "Verify this account with the device's administrators immediately; if unauthorized, remove it and rotate all other local credentials on this device.", "reason": "An unrecognized local account is a strong indicator of an already-successful compromise of the device's management plane."},
        ],
        "findingtags": ["network", "persistence", "local-accounts", "mitre-persistence"],
    },
    "missing-aaa": {
        "finding_type": "Missing Centralized AAA Enforcement",
        "title": "No AAA Authentication Enforcement Configured",
        "description": "The device's running-config has no `aaa authentication login` enforcement — management access falls back to local-only authentication (or none at all).",
        "why_this_matters": "Without centralized AAA, there's no single point to disable a compromised administrator credential, no centralized audit trail of who logged in when, and every device effectively becomes an independent, harder-to-govern authentication boundary.",
        "what_is_this": "A regex check of `show running-config` for the presence of an `aaa authentication login` line enforcing TACACS+/RADIUS.",
        "normal_behaviour": "`aaa authentication login` configured to use a centralized TACACS+/RADIUS group (with local as an explicit, documented fallback only).",
        "suspicious_behaviour": "No `aaa authentication login` line present at all, meaning the device relies solely on local accounts (or has no login authentication configured).",
        "mitre_technique_id": "T1078",
        "mitre_technique": "Valid Accounts",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 60,
        "recommendations": [
            {"priority": "medium", "action": "Configure `aaa authentication login` against a centralized TACACS+/RADIUS server, keeping local accounts as an explicit documented fallback only.", "reason": "Centralized AAA gives one place to revoke access and a single audit trail across the whole device fleet — critical during an incident."},
        ],
        "findingtags": ["network", "aaa", "defense-evasion"],
    },
}

ARTIFACT_KNOWLEDGE_BASE: Dict[str, Dict[str, Any]] = {**_BASELINE, **_RULE_FINDINGS}


def lookup(artifact_key: str) -> Dict[str, Any]:
    """Returns the KB entry for artifact_key, or GENERIC_FALLBACK on a miss.
    Callers should log a warning on a miss, mirroring Windows' behavior —
    logging itself lives in findings.py, not here, to keep this module a
    pure data lookup with no logging-framework dependency."""
    return ARTIFACT_KNOWLEDGE_BASE.get(artifact_key, GENERIC_FALLBACK)
