"""
ArtifactKnowledgeBase
"""
from __future__ import annotations

from typing import Any, Dict

GENERIC_FALLBACK: Dict[str, Any] = {
    "finding_type": "Unclassified Network Artifact",
    "category": "network",
    "title": "Unclassified Network Artifact",
    "description": "Raw artifact collected from a network device; no knowledge-base entry exists yet for this artifact key.",
    "why_this_matters": "Not yet documented — review the raw evidence directly.",
    "what_is_this": "An artifact collected by the Network Devices module that hasn't been catalogued in the knowledge base yet.",
    "normal_behaviour": "",
    "suspicious_behaviour": "",
    "mitre_technique_id": None,
    "mitre_technique": None,
    "mitre_tactic": None,
    "base_risk_score": 0,
    "recommendations": [],
    "findingtags": ["forensicator", "network", "uncatalogued"],
}

# ── Baseline collected artifacts (one per collectors/cisco_ios.py COMMANDS key) ──

_BASELINE: Dict[str, Dict[str, Any]] = {
    "version": {
        "finding_type": "Device Version and Hardware Information",
        "title": "Device Version and Hardware Information",
        "description": "Software version, uptime, and hardware identity reported by the device.",
        "why_this_matters": "Establishes exactly what's running for the rest of the investigation, and whether the device is on a version with known CVEs.",
        "what_is_this": "The device's version/hardware summary (OS version, uptime, hardware model, serial number) — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "A version matching the organization's approved software baseline.",
        "suspicious_behaviour": "An unexpectedly old version, an uptime that doesn't match a known maintenance window, or hardware/serial that doesn't match asset inventory.",
        "recommendations": [{"priority": "info", "action": "Cross-reference the reported version against the vendor's security advisories.", "reason": "Confirms whether this device is exposed to any known, unpatched vulnerability."}],
        "findingtags": ["network", "version", "hardware"],
    },
    "running-config": {
        "finding_type": "Full Running Configuration",
        "title": "Full Running Configuration",
        "description": "The device's complete active configuration, collected for keyword/drift review and as the source for several detection rules.",
        "why_this_matters": "The single most information-dense artifact collected — nearly every other finding on this device (ACLs, AAA, SNMP, local accounts) is derived from this text.",
        "what_is_this": "The device's full active configuration — see this finding's source.command for the exact command used on this platform (e.g. `show running-config` on Cisco/Arista, `show configuration` on Junos).",
        "normal_behaviour": "Matches the organization's configuration baseline/template for this device role.",
        "suspicious_behaviour": "Unexpected ACL entries, new NAT/PAT rules, unrecognized tunnel interfaces, or any drift from a known-good baseline.",
        "recommendations": [{"priority": "medium", "action": "Diff this configuration against the last known-good baseline for this device.", "reason": "Config drift is one of the most reliable indicators of unauthorized access to network infrastructure."}],
        "findingtags": ["network", "configuration"],
    },
    "sessions": {
        "finding_type": "Active Management Sessions",
        "title": "Active Management Sessions",
        "description": "Users/sessions currently logged into the device's management plane.",
        "why_this_matters": "Shows exactly who is on the device right now — directly relevant if this investigation is time-sensitive.",
        "what_is_this": "Active management-plane sessions — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Sessions from known administrator source addresses during expected hours.",
        "suspicious_behaviour": "A session from an unrecognized source address, or at an unusual time.",
        "recommendations": [],
        "findingtags": ["network", "sessions"],
    },
    "arp-table": {
        "finding_type": "ARP Cache",
        "title": "ARP Cache",
        "description": "IP-to-MAC mappings currently known to the device.",
        "why_this_matters": "Useful for tracing which physical/virtual host owned an IP address at collection time — relevant for pivoting to a specific endpoint.",
        "what_is_this": "The device's ARP cache — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Expected hosts, no MAC address duplicated across multiple IPs.",
        "suspicious_behaviour": "The same MAC address claiming multiple IPs (possible ARP spoofing), or an unrecognized vendor OUI on a supposedly locked-down segment.",
        "recommendations": [],
        "findingtags": ["network", "arp"],
    },
    "mac-address-table": {
        "finding_type": "MAC Address Table",
        "title": "MAC Address Table",
        "description": "Learned MAC addresses and the switchports they were seen on.",
        "why_this_matters": "Ties a MAC address to a physical port — useful for locating a device physically during response.",
        "what_is_this": "Learned MAC addresses and the switchports they were seen on — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Expected device count per port; access ports show one MAC, not dozens.",
        "suspicious_behaviour": "An access port suddenly showing many MAC addresses (possible rogue switch/hub plugged in), or MAC flapping between ports.",
        "recommendations": [],
        "findingtags": ["network", "mac-table"],
    },
    "ip-route": {
        "finding_type": "IP Routing Table",
        "title": "IP Routing Table",
        "description": "The device's current routing table.",
        "why_this_matters": "An unexpected route (especially a default route pointing somewhere new) can silently redirect traffic for interception.",
        "what_is_this": "The device's routing table — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Matches the expected routing design for this device/segment.",
        "suspicious_behaviour": "A static route not present in the baseline, or a default route pointing to an unexpected next-hop.",
        "recommendations": [],
        "findingtags": ["network", "routing"],
    },
    "access-lists": {
        "finding_type": "Access Control Lists",
        "title": "Access Control Lists",
        "description": "ACLs currently configured and active on the device.",
        "why_this_matters": "ACLs are often the only thing standing between a segment and the rest of the network — an overly broad rule undoes segmentation entirely.",
        "what_is_this": "The device's active traffic-filtering policy (ACLs on Cisco/Arista, firewall filters on Junos) — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Scoped permit/deny rules matching the intended security policy.",
        "suspicious_behaviour": "A broad `permit ip any any`-style rule, or an ACL that was recently modified without a corresponding change ticket.",
        "recommendations": [],
        "findingtags": ["network", "acl"],
    },
    "logging": {
        "finding_type": "Local Log Buffer",
        "title": "Local Log Buffer",
        "description": "Recent entries from the device's local logging buffer.",
        "why_this_matters": "May contain direct evidence of the incident (failed logins, config changes, interface flaps) even before any dedicated detection rule fires.",
        "what_is_this": "Recent entries from the device's local log buffer — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Routine operational messages.",
        "suspicious_behaviour": "Repeated authentication failures, unexpected config-change log lines, or a gap in the log timeline (possible log tampering).",
        "recommendations": [],
        "findingtags": ["network", "logging"],
    },
    "cdp-neighbors": {
        "finding_type": "CDP Neighbor Topology",
        "title": "CDP Neighbor Topology",
        "description": "Directly-connected neighbor devices as seen via CDP.",
        "why_this_matters": "An unexpected neighbor on a port that should be an end-host port can indicate a rogue switch or access point physically plugged into the network.",
        "what_is_this": "The output of `show cdp neighbors detail`.",
        "normal_behaviour": "Only expected infrastructure devices appear as neighbors on trunk/uplink ports; end-host ports show no CDP neighbor at all.",
        "suspicious_behaviour": "A switch or AP appearing as a neighbor on a port that's supposed to be a single end-host access port.",
        "recommendations": [],
        "findingtags": ["network", "topology", "cdp"],
    },
    "lldp-neighbors": {
        "finding_type": "LLDP Neighbor Topology",
        "title": "LLDP Neighbor Topology",
        "description": "Directly-connected neighbor devices as seen via LLDP — the vendor-neutral equivalent of CDP, used by Junos and available on Cisco/Arista alongside CDP.",
        "why_this_matters": "An unexpected neighbor on a port that should be an end-host port can indicate a rogue switch or access point physically plugged into the network.",
        "what_is_this": "The output of `show lldp neighbors detail`.",
        "normal_behaviour": "Only expected infrastructure devices appear as neighbors on trunk/uplink ports; end-host ports show no LLDP neighbor at all.",
        "suspicious_behaviour": "A switch or AP appearing as a neighbor on a port that's supposed to be a single end-host access port.",
        "recommendations": [],
        "findingtags": ["network", "topology", "lldp"],
    },
    "snmp-config": {
        "finding_type": "SNMP Configuration",
        "title": "SNMP Configuration",
        "description": "The device's current SNMP configuration and community/user list.",
        "why_this_matters": "SNMP with a weak or default community string is a well-known, trivial way to read (and on some setups, write) device configuration remotely.",
        "what_is_this": "The device's SNMP configuration — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "SNMPv3 with unique, non-default credentials, or SNMP disabled entirely.",
        "suspicious_behaviour": "A default community string (`public`/`private`), or SNMPv1/v2c in use instead of v3.",
        "recommendations": [],
        "findingtags": ["network", "snmp"],
    },
    "ssh-config": {
        "finding_type": "SSH Management Configuration",
        "title": "SSH Management Configuration",
        "description": "The device's SSH server configuration (version, timeouts, authentication retries).",
        "why_this_matters": "Confirms whether the intended secure management protocol is actually in effect and correctly hardened.",
        "what_is_this": "The device's SSH/management-access configuration — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "SSHv2 only, with a reasonable authentication-retry limit.",
        "suspicious_behaviour": "SSHv1 still permitted, or an unusually high authentication-retry count.",
        "recommendations": [],
        "findingtags": ["network", "ssh"],
    },
    "clock": {
        "finding_type": "Device Clock",
        "title": "Device Clock",
        "description": "The device's current system clock reading.",
        "why_this_matters": "Every timestamp collected from this device (logging, sessions, ARP) is only as trustworthy as this clock — a skewed clock undermines cross-device timeline correlation.",
        "what_is_this": "The device's current system clock reading — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Matches actual current time within a few seconds.",
        "suspicious_behaviour": "A clock that's significantly off from actual time.",
        "recommendations": [],
        "findingtags": ["network", "time"],
    },
    "ntp-associations": {
        "finding_type": "NTP Time Synchronization",
        "title": "NTP Time Synchronization",
        "description": "The device's configured NTP peers and their sync status.",
        "why_this_matters": "No working NTP sync means this device's timestamps can silently drift, undermining log correlation across the environment during an incident (the same concern the Windows/Linux/macOS collectors flag when NTP is misconfigured).",
        "what_is_this": "The device's configured NTP peers and sync status — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "At least one NTP peer reachable and synchronized (marked with `*` in IOS output).",
        "suspicious_behaviour": "No peers configured, or all configured peers unreachable/unsynchronized.",
        "recommendations": [{"priority": "low", "action": "Configure and verify at least one reachable, synchronized NTP source.", "reason": "Reliable timestamps are a prerequisite for correlating this device's logs with everything else collected during the investigation."}],
        "findingtags": ["network", "ntp", "time"],
    },
    "event-manager": {
        "finding_type": "Event/Automation Policy Configuration",
        "title": "Event/Automation Policy Configuration",
        "description": "Registered event-manager policies, task-scheduler entries, or event-options — the device's own scriptable automation/trigger mechanism (EEM on Cisco, event-options on Junos, task-scheduler on VyOS).",
        "why_this_matters": "Scheduled/triggered logic blocks are among the most durable and stealthy persistence mechanisms on network gear — they can reinject config, suppress output, or execute on syslog/CLI/timer events, effectively giving code execution tied to device events.",
        "what_is_this": "The device's registered event/automation policies — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Only documented, change-ticketed automation policies present.",
        "suspicious_behaviour": "Any policy not in the expected_eem_applets/expected_scheduler_tasks baseline, especially one triggered on syslog or CLI patterns, or whose action touches AAA/logging/ACL config.",
        "recommendations": [],
        "findingtags": ["network", "persistence", "automation"],
    },
    "flash-listing": {
        "finding_type": "Persistent Storage Listing",
        "title": "Persistent Storage Listing",
        "description": "Files present in the device's flash/bootflash/persistent storage.",
        "why_this_matters": "Extra binaries or scripts staged on-device are commonly used to reload implants or serve as a dropped tool for further access.",
        "what_is_this": "A directory listing of the device's persistent storage — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Only expected images/config backups tied to a documented upgrade or change.",
        "suspicious_behaviour": "Recently-modified files not tied to a documented change, or generic/obfuscated filenames.",
        "recommendations": [],
        "findingtags": ["network", "integrity", "filesystem"],
    },
    "span-sessions": {
        "finding_type": "Traffic Mirror Session Configuration",
        "title": "Traffic Mirror Session Configuration",
        "description": "SPAN/RSPAN/ERSPAN or port-mirroring sessions currently configured.",
        "why_this_matters": "A mirror session lets an attacker copy live traffic off the wire for exfiltration or credential harvesting without compromising every endpoint.",
        "what_is_this": "The device's configured traffic mirror sessions — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Only documented mirror sessions matching the expected_span_sessions baseline.",
        "suspicious_behaviour": "A new session mirroring an uplink or server VLAN to an unexpected destination.",
        "recommendations": [],
        "findingtags": ["network", "collection", "span"],
    },
    "device-sockets": {
        "finding_type": "Device-Originated Network Connections",
        "title": "Device-Originated Network Connections",
        "description": "Sockets/connections the device itself has open as a client, not just as a managed target.",
        "why_this_matters": "Network devices aren't supposed to be network clients beyond a small known set of management/telemetry services — a self-originated connection to an arbitrary IP is a strong implant/C2 indicator (seen in VPNFilter-class malware).",
        "what_is_this": "The device's own outbound/local socket table — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "Only connections to expected management/telemetry destinations (NTP, syslog, AAA, SNMP trap receivers).",
        "suspicious_behaviour": "A locally-sourced connection to an IP outside the expected_device_outbound_destinations baseline.",
        "recommendations": [],
        "findingtags": ["network", "c2"],
    },
    "config-diff": {
        "finding_type": "Running vs. Saved Configuration Difference",
        "title": "Running vs. Saved Configuration Difference",
        "description": "Differences between the device's active running configuration and its saved/startup configuration (or, on VyOS, its recent commit history).",
        "why_this_matters": "A live-only change that was never saved suggests either an in-progress unauthorized modification, or deliberate avoidance of persistence to reduce detection on the next config backup — either way it needs review.",
        "what_is_this": "The device's running-vs-saved config diff — see this finding's source.command for the exact command used on this platform.",
        "normal_behaviour": "No difference, or differences fully explained by an approved, in-progress change window.",
        "suspicious_behaviour": "Unexplained differences, especially touching AAA, ACL, interface, or routing sections.",
        "recommendations": [],
        "findingtags": ["network", "config-drift"],
    },
}

# ── Detection-rule findings (keyed by the rule id in rules/rules.json) ──

_RULE_FINDINGS: Dict[str, Dict[str, Any]] = {
    "insecure-mgmt-plane": {
        "finding_type": "Insecure Management Plane",
        "title": "Telnet Enabled or VTY Lines Without Source Restriction",
        "description": "The device's running-config permits Telnet management access, and/or has VTY lines with no access-class restricting which source addresses may connect.",
        "why_this_matters": "Telnet transmits credentials in plaintext, and an unrestricted VTY line means anyone who can route to the device's management IP can attempt to log in — both dramatically widen the attack surface on the device that, if compromised, controls the network itself.",
        "what_is_this": "A regex scan of `show running-config` for `transport input telnet` (or `transport input all`) on a `line vty` block, and for `line vty` blocks with no `access-class` statement.",
        "normal_behaviour": "`transport input ssh` only, with every VTY line restricted by an `access-class` ACL to known management-source addresses.",
        "suspicious_behaviour": "Telnet permitted, or a VTY line reachable from any source address.",
        "mitre_technique_id": "T1021.001",
        "mitre_technique": "Remote Services: Remote Desktop Protocol",
        "mitre_tactic": "Lateral Movement",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Remove `transport input telnet` from every VTY line; restrict to `transport input ssh`.", "reason": "Telnet's plaintext credentials can be captured by anyone able to observe the management network path."},
            {"priority": "high", "action": "Apply an `access-class` ACL to every VTY line, scoped to known management-source addresses only.", "reason": "Prevents management-plane login attempts from anywhere other than trusted, expected sources."},
        ],
        "findingtags": ["network", "management-plane", "telnet", "mitre-lateral-movement"],
    },
    "weak-snmp-community": {
        "finding_type": "Weak or Default SNMP Community",
        "title": "Default or Weak SNMP Community String In Use",
        "description": "The device's running-config includes an SNMP community string matching a common default (`public`/`private`), and/or SNMPv1/v2c is configured instead of SNMPv3.",
        "why_this_matters": "A default SNMP community string is one of the most well-known, trivially exploitable network-device weaknesses — it can allow an attacker to read (and depending on the community's permissions, write) device configuration without ever needing to log in.",
        "what_is_this": "A regex scan of `show running-config` for `snmp-server community public`/`private` lines and for the absence of any `snmp-server group ... v3` configuration.",
        "normal_behaviour": "SNMPv3 with unique, non-default credentials, or SNMP disabled entirely if not needed.",
        "suspicious_behaviour": "Any `snmp-server community` line using `public` or `private`, or SNMPv1/v2c configured at all.",
        "mitre_technique_id": "T1552.001",
        "mitre_technique": "Unsecured Credentials: Credentials In Files",
        "mitre_tactic": "Credential Access",
        "base_risk_score": 70,
        "recommendations": [
            {"priority": "high", "action": "Remove any `public`/`private` SNMP community and migrate to SNMPv3 with unique credentials.", "reason": "Default community strings are the first thing scanned for by both automated malware and manual attackers targeting network infrastructure."},
        ],
        "findingtags": ["network", "snmp", "credential-access"],
    },
    "unauthorized-local-accounts": {
        "finding_type": "Unauthorized Local Account",
        "title": "Local Account Not on the Expected Baseline",
        "description": "A `username` entry exists in running-config that isn't present in this device's (or the global) baselines.expected_local_users allow-list in config.json.",
        "why_this_matters": "An unexpected local account is one of the most direct signs of unauthorized persistent access to network infrastructure — unlike a compromised centralized-AAA credential, a rogue local account survives even if every other credential in the environment is rotated.",
        "what_is_this": "The set of local user accounts extracted from this device's running config (syntax varies by vendor — see this finding's source.command), diffed against config.json's baselines.expected_local_users baseline for this device.",
        "normal_behaviour": "Every local account present matches the configured baseline exactly.",
        "suspicious_behaviour": "Any local account present in running-config that isn't in the baseline list.",
        "mitre_technique_id": "T1136.001",
        "mitre_technique": "Create Account: Local Account",
        "mitre_tactic": "Persistence",
        "base_risk_score": 90,
        "recommendations": [
            {"priority": "critical", "action": "Verify this account with the device's administrators immediately; if unauthorized, remove it and rotate all other local credentials on this device.", "reason": "An unrecognized local account is a strong indicator of an already-successful compromise of the device's management plane."},
        ],
        "findingtags": ["network", "persistence", "local-accounts", "mitre-persistence"],
    },
    "missing-aaa": {
        "finding_type": "Missing Centralized AAA Enforcement",
        "title": "No AAA Authentication Enforcement Configured",
        "description": "The device's running-config has no `aaa authentication login` enforcement — management access falls back to local-only authentication (or none at all).",
        "why_this_matters": "Without centralized AAA, there's no single point to disable a compromised administrator credential, no centralized audit trail of who logged in when, and every device effectively becomes an independent, harder-to-govern authentication boundary.",
        "what_is_this": "A regex check of `show running-config` for the presence of an `aaa authentication login` line enforcing TACACS+/RADIUS.",
        "normal_behaviour": "`aaa authentication login` configured to use a centralized TACACS+/RADIUS group (with local as an explicit, documented fallback only).",
        "suspicious_behaviour": "No `aaa authentication login` line present at all, meaning the device relies solely on local accounts (or has no login authentication configured).",
        "mitre_technique_id": "T1078",
        "mitre_technique": "Valid Accounts",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 60,
        "recommendations": [
            {"priority": "medium", "action": "Configure `aaa authentication login` against a centralized TACACS+/RADIUS server, keeping local accounts as an explicit documented fallback only.", "reason": "Centralized AAA gives one place to revoke access and a single audit trail across the whole device fleet — critical during an incident."},
        ],
        "findingtags": ["network", "aaa", "defense-evasion"],
    },
    "logic-implant-persistence": {
        "finding_type": "Logic Implant Present (Event/Automation Policy)",
        "title": "Unbaselined Event/Automation Policy (Logic Implant)",
        "description": "An event-manager policy, task-scheduler entry, or event-options policy is registered that isn't in config.json's expected_eem_applets/expected_scheduler_tasks baseline.",
        "why_this_matters": "Scheduled/triggered logic blocks are among the most durable and stealthy implant mechanisms on network gear — they can reinject config, hide output, or execute on syslog/CLI/timer events, effectively giving code execution tied to device events.",
        "what_is_this": "Registered event/automation policies on this device — see this finding's source.command.",
        "normal_behaviour": "Only documented, change-ticketed automation policies present.",
        "suspicious_behaviour": "Any policy not in the baseline, especially one triggered on syslog/CLI patterns or whose action touches AAA/logging/ACL config.",
        "mitre_technique_id": "T1053",
        "mitre_technique": "Scheduled Task/Job",
        "mitre_tactic": "Persistence",
        "base_risk_score": 92,
        "recommendations": [
            {"priority": "critical", "action": "Review this policy's trigger and action with the device's administrators immediately; remove if unauthorized.", "reason": "An unbaselined event/automation policy is one of the stealthiest persistence mechanisms available on network infrastructure."},
        ],
        "findingtags": ["network", "persistence", "automation", "mitre-persistence"],
    },
    "boot-image-tampering": {
        "finding_type": "Boot Image Path Modified",
        "title": "Boot Statement Points Outside Expected Image Path",
        "description": "A `boot system`/boot statement in running-config points somewhere other than config.json's expected_boot_image_path.",
        "why_this_matters": "Repointing the boot image to a modified firmware image or a TFTP/FTP path ensures an implant survives a reload.",
        "what_is_this": "Boot statements extracted from running-config — see this finding's source.command.",
        "normal_behaviour": "Boot statement(s) match the expected flash-local image path.",
        "suspicious_behaviour": "A boot statement pointing to a TFTP/FTP path, or a flash path outside the expected baseline.",
        "mitre_technique_id": "T1542.005",
        "mitre_technique": "Pre-OS Boot: TFTP Boot",
        "mitre_tactic": "Persistence",
        "base_risk_score": 92,
        "recommendations": [
            {"priority": "critical", "action": "Verify the boot path against the expected image location immediately; a TFTP/FTP boot path in particular should never be present outside an active, supervised upgrade.", "reason": "A modified boot path can silently load a compromised firmware image on every reload."},
        ],
        "findingtags": ["network", "integrity", "boot", "mitre-persistence"],
    },
    "image-hash-mismatch": {
        "finding_type": "Running Image Hash Mismatch",
        "title": "Running Image Does Not Match Known-Good Hash",
        "description": "The device's running image hash doesn't match any entry in config.json's known_good_image_hashes baseline. Best-effort: computing this requires a separate hash/verify command scoped to the exact image filename (only known after collection), so this check only runs when that baseline is explicitly populated with a hash to compare against — it does not compute or discover hashes on its own.",
        "why_this_matters": "Firmware/image implants patch the OS image itself, surviving reloads and evading config-only review.",
        "what_is_this": "The device's reported image version/filename from `show version` — see this finding's source.command. Full cryptographic verification (e.g. IOS-XE's `show software authenticity running`) requires a follow-up command this single-pass collector doesn't issue automatically; treat this finding as a prompt to verify manually, not a completed hash check.",
        "normal_behaviour": "Image version/filename matches an approved release.",
        "suspicious_behaviour": "An image version/filename not on the approved list, or evidence of authenticity-check failure if that command's output was manually reviewed.",
        "mitre_technique_id": "T1601.001",
        "mitre_technique": "Modify System Image: Patch System Image",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 92,
        "recommendations": [
            {"priority": "critical", "action": "Manually verify this image's hash/authenticity against the vendor-published value for this exact version.", "reason": "A patched system image is one of the highest-impact, hardest-to-detect compromises possible on network infrastructure."},
        ],
        "findingtags": ["network", "integrity", "image", "mitre-defense-evasion"],
    },
    "unexpected-flash-files": {
        "finding_type": "Unexpected File in Persistent Storage",
        "title": "File Present in Flash/Bootflash Not on Baseline",
        "description": "A file listed in the device's persistent storage isn't in config.json's expected_flash_files baseline.",
        "why_this_matters": "Extra binaries/scripts staged on-device are commonly used to reload implants or serve as a dropped tool for further access.",
        "what_is_this": "A directory listing of persistent storage — see this finding's source.command.",
        "normal_behaviour": "Only expected images/config backups tied to a documented change.",
        "suspicious_behaviour": "A recently-modified file not tied to a documented upgrade, or a generic/obfuscated filename.",
        "mitre_technique_id": "T1105",
        "mitre_technique": "Ingress Tool Transfer",
        "mitre_tactic": "Command and Control",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Verify this file's origin with the device's administrators; remove if not tied to a documented change.", "reason": "Files staged outside the expected baseline are commonly used to reload implants after a reboot or factory-reset attempt."},
        ],
        "findingtags": ["network", "integrity", "filesystem", "mitre-c2"],
    },
    "logging-tampering": {
        "finding_type": "Logging Disabled or Reduced",
        "title": "Logging Disabled, Severity Reduced, or Buffer Shrunk",
        "description": "running-config shows logging disabled, a reduced trap/buffer severity, or a smaller buffer size than config.json's expected_min_logging_buffer/expected_min_logging_severity baseline.",
        "why_this_matters": "Reducing/disabling logging is direct anti-forensics — it removes the evidence trail investigators need to reconstruct attacker activity.",
        "what_is_this": "Logging configuration extracted from running-config — see this finding's source.command.",
        "normal_behaviour": "Logging enabled at or above the expected severity/buffer size.",
        "suspicious_behaviour": "A `no logging` statement, a buffer size decrease, or a severity level reduction versus baseline.",
        "mitre_technique_id": "T1562",
        "mitre_technique": "Impair Defenses",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Restore logging to the expected severity/buffer size immediately and review what activity may have gone unrecorded.", "reason": "A logging gap during exactly the window an attacker needed it is rarely coincidental."},
        ],
        "findingtags": ["network", "anti-forensics", "logging", "mitre-defense-evasion"],
    },
    "syslog-destination-changed": {
        "finding_type": "Syslog Destination Removed or Changed",
        "title": "Syslog Destination Missing or Points Outside Expected SIEM",
        "description": "running-config's logging host/server lines don't match config.json's expected_syslog_servers baseline.",
        "why_this_matters": "Killing or redirecting centralized logging blinds the SOC/SIEM to further activity on this device.",
        "what_is_this": "Configured syslog destinations extracted from running-config — see this finding's source.command.",
        "normal_behaviour": "Every configured syslog destination matches the expected SIEM/collector baseline.",
        "suspicious_behaviour": "A missing expected destination, or a new destination IP outside known SIEM infrastructure.",
        "mitre_technique_id": "T1562",
        "mitre_technique": "Impair Defenses",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Restore the expected syslog destination(s) and investigate why/when it changed.", "reason": "A redirected or removed syslog destination silently blinds centralized detection for this device going forward."},
        ],
        "findingtags": ["network", "anti-forensics", "logging", "mitre-defense-evasion"],
    },
    "ntp-tampering": {
        "finding_type": "NTP Disabled or Rogue Server",
        "title": "NTP Server Missing From Baseline or Sync Lost",
        "description": "Configured NTP servers don't match config.json's expected_ntp_servers baseline, or no peer is currently synchronized.",
        "why_this_matters": "Accurate time sync is required to correlate events across the environment during an incident; breaking it quietly complicates timeline reconstruction.",
        "what_is_this": "The device's NTP peer/sync status — see this finding's source.command.",
        "normal_behaviour": "Every configured NTP server matches the expected baseline, with at least one synchronized peer.",
        "suspicious_behaviour": "An NTP server outside the baseline, or no synchronized peer at all.",
        "mitre_technique_id": "T1070",
        "mitre_technique": "Indicator Removal",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 50,
        "recommendations": [
            {"priority": "medium", "action": "Restore the expected NTP configuration and verify sync status.", "reason": "Unreliable timestamps undermine correlating this device's logs with everything else collected during the investigation."},
        ],
        "findingtags": ["network", "anti-forensics", "ntp", "mitre-defense-evasion"],
    },
    "active-session-unexpected-source": {
        "finding_type": "Active Session From Unexpected Source",
        "title": "Management Session From Outside Expected IP Range",
        "description": "An active management session's source IP isn't within config.json's expected_management_ip_ranges baseline.",
        "why_this_matters": "Devices should only be managed from a small, known set of jump hosts/VLANs; a session outside that range is a strong compromise indicator.",
        "what_is_this": "Active management sessions extracted from this device's session list — see this finding's source.command.",
        "normal_behaviour": "Every active session's source IP falls within the expected management range(s).",
        "suspicious_behaviour": "A session from a source IP outside the expected range, especially with privileged access.",
        "mitre_technique_id": "T1133",
        "mitre_technique": "External Remote Services",
        "mitre_tactic": "Initial Access",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Confirm this session's source and account with the device's administrators immediately; terminate if unrecognized.", "reason": "A live session from an unexpected source is one of the few findings that may represent an ACTIVE, in-progress compromise rather than a historical one."},
        ],
        "findingtags": ["network", "management-plane", "mitre-initial-access"],
    },
    "aaa-fallback-abuse": {
        "finding_type": "AAA Fallback to Local Authentication",
        "title": "Local Login Shortly After AAA Server Unreachable",
        "description": "The log buffer shows both an AAA/TACACS/RADIUS-unreachable event and a local-account login in the same buffer window.",
        "why_this_matters": "\"Kill the AAA server, then log in locally\" bypasses centralized auth logging/MFA and is rarely coincidental.",
        "what_is_this": "A co-occurrence check against the device's log buffer — see this finding's source.command. Simplified: checks that both event types appear in the currently-retained log buffer, not a precise timestamp-window correlation (the buffer itself is usually short enough that co-occurrence is already a meaningful signal).",
        "normal_behaviour": "No AAA-unreachable events, or AAA-unreachable events with no corresponding local login nearby.",
        "suspicious_behaviour": "An AAA-unreachable event and a local-account login both present in the retained log buffer.",
        "mitre_technique_id": "T1556",
        "mitre_technique": "Modify Authentication Process",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 92,
        "recommendations": [
            {"priority": "critical", "action": "Confirm this login with the account owner and investigate why AAA was unreachable at that time.", "reason": "This pattern is a well-known technique for bypassing centralized authentication logging/MFA."},
        ],
        "findingtags": ["network", "aaa-credential", "mitre-defense-evasion"],
    },
    "brute-force-pattern": {
        "finding_type": "Repeated Authentication Failures Followed by Success",
        "title": "Brute-Force Login Pattern Detected",
        "description": "The log buffer shows authentication failures at or above config.json's brute_force_failure_threshold, followed by a successful login.",
        "why_this_matters": "A failure-then-success pattern in a short window is a strong brute-force signature, especially against privileged accounts.",
        "what_is_this": "Authentication failure/success events extracted from the device's log buffer — see this finding's source.command.",
        "normal_behaviour": "No clustered authentication failures, or failures with no following success.",
        "suspicious_behaviour": "Failures at or above the configured threshold followed by a success in the same buffer window.",
        "mitre_technique_id": "T1110",
        "mitre_technique": "Brute Force",
        "mitre_tactic": "Credential Access",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Confirm the successful login's account/source with the device's administrators; rotate the credential if unrecognized.", "reason": "A brute-force-then-success pattern often means the account is now compromised, not just targeted."},
        ],
        "findingtags": ["network", "aaa-credential", "mitre-credential-access"],
    },
    "unexpected-span-session": {
        "finding_type": "Unexpected Traffic Mirror Session",
        "title": "SPAN/Mirror Session Not on Baseline",
        "description": "A configured SPAN/RSPAN/ERSPAN or port-mirroring session isn't in config.json's expected_span_sessions baseline.",
        "why_this_matters": "Mirror sessions let an attacker copy live traffic off the wire for exfiltration or credential harvesting without compromising every endpoint.",
        "what_is_this": "Configured mirror sessions — see this finding's source.command.",
        "normal_behaviour": "Only documented mirror sessions matching the baseline.",
        "suspicious_behaviour": "A new session mirroring an uplink or server VLAN to an unexpected destination.",
        "mitre_technique_id": "T1040",
        "mitre_technique": "Network Sniffing",
        "mitre_tactic": "Collection",
        "base_risk_score": 92,
        "recommendations": [
            {"priority": "critical", "action": "Verify this mirror session's destination with the device's administrators immediately; remove if unauthorized.", "reason": "A rogue mirror session can silently exfiltrate every packet crossing the mirrored port or VLAN."},
        ],
        "findingtags": ["network", "traffic-manipulation", "mitre-collection"],
    },
    "unexpected-tunnel-interface": {
        "finding_type": "Unexpected Tunnel Interface",
        "title": "GRE/IPsec/VXLAN Tunnel Not on Baseline",
        "description": "A tunnel interface's source/destination pair isn't in config.json's expected_tunnel_endpoints baseline.",
        "why_this_matters": "Rogue tunnels are a low-visibility way to exfiltrate data or maintain covert C2, blending in with legitimate WAN/VPN traffic.",
        "what_is_this": "Tunnel interfaces extracted from running-config — see this finding's source.command.",
        "normal_behaviour": "Every tunnel interface's endpoints match the approved baseline.",
        "suspicious_behaviour": "A tunnel interface with a source/destination pair outside the approved endpoint list.",
        "mitre_technique_id": "T1572",
        "mitre_technique": "Protocol Tunneling",
        "mitre_tactic": "Command and Control",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Verify this tunnel's endpoints with the device's administrators; remove if unauthorized.", "reason": "An unapproved tunnel can carry C2 or exfiltrated data disguised as normal WAN/VPN traffic."},
        ],
        "findingtags": ["network", "traffic-manipulation", "mitre-c2"],
    },
    "acl-loosened": {
        "finding_type": "Overly Broad ACL Entry",
        "title": "Broad Permit Statement in Access Control List",
        "description": "The device's active ACLs contain a `permit ip any any`-style entry (or equivalent), which is almost always a mistake or a deliberate loosening of segmentation.",
        "why_this_matters": "Quiet ACL loosening directly opens a path for further access or exfiltration while everything else looks normal.",
        "what_is_this": "Active ACL entries — see this finding's source.command. Simplified single-pass keyword detection (an overly broad permit statement), not a true diff against a stored prior-run baseline — this collector doesn't persist state between runs.",
        "normal_behaviour": "Only scoped permit/deny rules matching the intended security policy.",
        "suspicious_behaviour": "Any broad `permit ip any any`-style rule, especially on an edge/outbound ACL.",
        "mitre_technique_id": "T1562.004",
        "mitre_technique": "Impair Defenses: Disable or Modify System Firewall",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 92,
        "recommendations": [
            {"priority": "critical", "action": "Verify this rule against a documented change ticket immediately; tighten if unauthorized.", "reason": "An overly broad ACL entry can silently undo network segmentation while every other control still looks intact."},
        ],
        "findingtags": ["network", "traffic-manipulation", "acl", "mitre-defense-evasion"],
    },
    "device-outbound-c2": {
        "finding_type": "Device-Initiated Outbound Connection",
        "title": "Device-Originated Connection to Unexpected Destination",
        "description": "The device itself has an open outbound connection to a destination outside config.json's expected_device_outbound_destinations baseline.",
        "why_this_matters": "Devices aren't supposed to be network clients beyond a small known set of management services; self-originated connections to arbitrary IPs are a strong implant/C2 indicator (seen in VPNFilter-class malware).",
        "what_is_this": "The device's own socket/connection table — see this finding's source.command.",
        "normal_behaviour": "Only connections to expected management/telemetry destinations.",
        "suspicious_behaviour": "A locally-sourced connection to an IP outside the expected baseline.",
        "mitre_technique_id": "T1071",
        "mitre_technique": "Application Layer Protocol",
        "mitre_tactic": "Command and Control",
        "base_risk_score": 92,
        "recommendations": [
            {"priority": "critical", "action": "Identify the destination and owning process immediately; isolate the device if the destination can't be explained.", "reason": "A device-originated connection to an unexpected destination is one of the strongest possible indicators of an active network-device implant."},
        ],
        "findingtags": ["network", "c2", "mitre-c2"],
    },
    "config-drift-running-vs-startup": {
        "finding_type": "Running Config Differs From Saved Config",
        "title": "Unsaved Configuration Change",
        "description": "The device's running configuration differs from its saved/startup configuration. This is a raw diff-presence check — it does not weigh the change against a maintenance/change window, since none is currently configurable.",
        "why_this_matters": "A live-only change that was never saved suggests either an in-progress unauthorized modification, or deliberate avoidance of persistence to reduce detection on the next config backup.",
        "what_is_this": "The device's running-vs-saved diff — see this finding's source.command.",
        "normal_behaviour": "No difference, or a difference fully explained by an approved, in-progress change window.",
        "suspicious_behaviour": "An unexplained difference, especially touching AAA, ACL, interface, or routing configuration.",
        "mitre_technique_id": "T1562",
        "mitre_technique": "Impair Defenses",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 50,
        "recommendations": [
            {"priority": "medium", "action": "Review the diff's contents with the device's administrators and save (or revert) as appropriate.", "reason": "An unexplained live-only change is either an in-progress unauthorized modification or a deliberate attempt to avoid leaving a saved-config trail."},
        ],
        "findingtags": ["network", "config-drift", "mitre-defense-evasion"],
    },
    "config-section-hash-mismatch": {
        "finding_type": "Config Section Hash Mismatch",
        "title": "AAA/ACL/Routing Section Changed Since Baseline",
        "description": "A SHA-256 hash of this device's AAA, ACL, or routing configuration lines doesn't match the corresponding entry in config.json's baseline_section_hashes.",
        "why_this_matters": "Section-level hashing gives a fast, low-false-positive way to flag drift in the highest-risk config sections without diffing the whole config every run.",
        "what_is_this": "SHA-256 hashes computed over this device's AAA/ACL/routing-related lines in running-config, compared against the configured baseline hash for each section.",
        "normal_behaviour": "Every section's hash matches its baseline.",
        "suspicious_behaviour": "Any section's hash differs from its baseline — cross-reference against the unauthorized-local-accounts, insecure-mgmt-plane, and acl-loosened findings for this device.",
        "mitre_technique_id": "T1562",
        "mitre_technique": "Impair Defenses",
        "mitre_tactic": "Defense Evasion",
        "base_risk_score": 75,
        "recommendations": [
            {"priority": "high", "action": "Identify what changed in the flagged section and confirm it against a documented change ticket.", "reason": "Section-hash drift in AAA/ACL/routing config is a fast, reliable signal that something in a high-risk area of the config changed since the baseline was established."},
        ],
        "findingtags": ["network", "config-drift", "mitre-defense-evasion"],
    },
    "transit-known-malicious-destination": {
        "finding_type": "Transit Connection to Known-Malicious Destination",
        "title": "Forwarded Traffic to Known-Malicious IP",
        "description": "This device's NAT/conntrack session table shows a connection — forwarded on behalf of a host behind this device, not originated by the device itself — to an IP on the configured threat-intel blocklist (config.json's threat_intel.malicious_ip_sources / custom_malicious_ips.txt).",
        "why_this_matters": "A host behind this device reaching known C2/malware infrastructure is an active-compromise indicator on your network, distinct from the device itself being compromised — device-outbound-c2 only sees the device's own sockets and would miss this entirely.",
        "what_is_this": "The device's NAT translation table (Cisco IOS/IOS-XE) or conntrack table (VyOS) — the only real, read-only, per-vendor mechanism this collector found for visibility into traffic merely transiting the device. See this finding's source.command.",
        "normal_behaviour": "No session in the table has an endpoint on the loaded blocklist.",
        "suspicious_behaviour": "Any session with an endpoint matching a blocklist IP or CIDR — check the session's local/internal endpoint to identify which host behind this device is compromised.",
        "mitre_technique_id": "T1071",
        "mitre_technique": "Application Layer Protocol",
        "mitre_tactic": "Command and Control",
        "base_risk_score": 90,
        "recommendations": [
            {"priority": "critical", "action": "Identify and isolate the internal host shown in the session table entry; treat it as compromised until proven otherwise.", "reason": "A live connection to a known-malicious IP from a host on your network is a high-confidence active-compromise signal, not a policy violation."},
            {"priority": "medium", "action": "Confirm config.json's blocklist source(s) are current — a stale feed both misses new C2 infrastructure and can't be trusted as exhaustive.", "reason": "This rule is only as good as the threat-intel data it's checked against."},
        ],
        "findingtags": ["network", "c2", "transit", "mitre-c2"],
    },
}

ARTIFACT_KNOWLEDGE_BASE: Dict[str, Dict[str, Any]] = {**_BASELINE, **_RULE_FINDINGS}


def lookup(artifact_key: str) -> Dict[str, Any]:
    """Returns the KB entry for artifact_key, or GENERIC_FALLBACK on a miss.
    Callers should log a warning on a miss, mirroring Windows' behavior —
    logging itself lives in findings.py, not here, to keep this module a
    pure data lookup with no logging-framework dependency."""
    return ARTIFACT_KNOWLEDGE_BASE.get(artifact_key, GENERIC_FALLBACK)
